#@ load("@ytt:data", "data")

version: "3.7"

services:
  db:
    image: mariadb:10.3
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - data:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  fpm:
    build: ./fpm
    image: #@ "{}/nextcloud:{}".format(data.values.registry, data.values.fpm.version)
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - www:/var/www/html
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: db
    env_file:
      - db.env

  proxy:
    build: ./proxy
    image: #@ "{}/nc-proxy:{}".format(data.values.registry, data.values.proxy.version)
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.port: "80"
        traefik.frontend.rule: #@ "Host: {}".format(data.values.domain)
        traefik.frontend.headers.customResponseHeaders: Strict-Transport-Security:15552000
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
        traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/
    networks:
      - proxy_net
      - default
    configs:
      - source: nginx_nextcloud_conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    volumes:
      - type: volume
        source: www
        target: /var/www/html
        volume:
          nocopy: true

configs:
  nginx_nextcloud_conf:
    file: proxy/files/nextcloud.conf
  nginx_conf:
    file: proxy/files/nginx.conf

volumes: {data, www, logs, cache, db}

networks:
  proxy_net:
    external: true
